# .streamlit/config.toml
[theme]
base="light"
primaryColor="#FF4B4B" # Streamlit's default red, or choose another accent color
backgroundColor="#FFFFFF" # Force white background for main app
secondaryBackgroundColor="#F8F8F8" # A very light grey for secondary elements like tab background
textColor="#26272E" # Dark text for contrast on light background
font="sans serif"

[client]
toolbarMode = "off" # To remove the deploy button
[streamlit]
toolbarMode = "off"